version: '3.8'
services:
  hof-ukvic-app:
    env_file: devcontainer.env
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: Dockerfile
    
    networks:
      - ukvic-shared-network
    ports:
      - "8080:8080"
    hostname: hof-app
    depends_on:
      - redis
      #- file-vault

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: sleep infinity

  redis:
    image: "redis:alpine"
    networks:
      - ukvic-shared-network
    hostname: hof-redis
    ports:
      - "6379:6379"

  file-vault:
    env_file: devcontainer.env
    image: quay.io/ukhomeofficedigital/file-vault:f4cd1ece1caddc3bfbc8f5db761c593fda79ef12
    networks:
      - ukvic-shared-network
    hostname: hof-file-vault
    environment:
      - DEBUG=*
    ports:
      - "3000:3000"

  rds-api:
    image: quay.io/ukhomeofficedigital/hof-rds-api:3.2.0@sha256:1c6bc4ce06660d0e061d49bffffdcaf71c3abefe935d85f6dadc8ff87dd52323
    networks:
      - ukvic-shared-network
    hostname: hof-rds-api
    environment:
      - SERVICE_NAME=ukvic
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=hof-postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=ukvic
    ports:
      - "5000:5000"
    healthcheck:
      disable: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14@sha256:8396ed98bfbeb08ff9c83a4de368957af98085f55d2c93e7e83828595d6f6663
    networks:
      - ukvic-shared-network
    hostname: hof-postgres
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ukvic
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  sqs-mock:
    build:
      context: ../test/_integration/sqs-mock
    container_name: sqs-mock
    networks:
      - ukvic-shared-network
    ports:
      - "9324:9324"

networks:
  ukvic-shared-network:
    driver: bridge

volumes:
  pgdata:
