---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: data-service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: data-service
  {{ end }}
{{ file .DATA_SERVICE_INTERNAL_ANNOTATIONS | indent 2 }}
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
        - ukvic-data-service.internal.sas.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - ukvic-data-service.internal.stg.sas.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - ukvic-data-service.uat.internal.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - data-service-{{ .DRONE_SOURCE_BRANCH }}.branch.internal.sas-notprod.homeoffice.gov.uk
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-internal
      {{ else }}
      secretName: data-service-cert-cmio
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
    - host: ukvic-data-service.internal.sas.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: data-service.stg.internal.ukvi-complaints.sas.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: ukvic-data-service.uat.internal.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: data-service-{{ .DRONE_SOURCE_BRANCH }}.branch.internal.sas-notprod.homeoffice.gov.uk
    {{ end }}
      http:
        paths:
          - path: /
            backend: 
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: data-service-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: data-service
              {{ end }}
              servicePort: 10443
